version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.0-node
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.2.0-node
      - image: circleci/postgres:12.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "123123"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create Database
          command: bundle exec rails db:create
      - run:
          name: Database Setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: RSpec Testing
          command: bundle exec rspec --backtrace --fail-fast

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
